In [1]:
from elasticsearch import Elasticsearch
# es = Elasticsearch("http://localhost:9200",
# basic_auth = ('elasticsearch', 'e3TKzHmKRFWBP4gY--cjeQ'),
# ca_certs = 'C:/Users/lenovo/Downloads/elasticsearch-9.1.3-windows-x86_64/elasticsearch-9.1.3/config/certs/http_ca.crt'
# )
es = Elasticsearch("http://localhost:9200",
                   basic_auth = ('elasticsearch', 'e3TKzHmKRFWBP4gY--cjeQ')
                   )
es.ping()

True

## Prepare the data

In [6]:
import pandas as pd
df = pd.read_csv('./src/marathi_dataset.csv')
print(df.shape)
df.head()

(30, 7)

,scheme_id,scheme_name,description,department,category,eligibility,deadline
0,1,शेतकरी अनुदान योजना,बियाण्यांसाठी शेतकऱ्यांना आर्थिक मदत देणारी योजना,कृषी विभाग,अनुदान,जमीन धारक शेतकरी,3/31/2024
1,2,महिला स्वसहाय्य गट योजना,महिला स्वसहाय्य गटांना व्यवसाय सुरू करण्यासाठी...,महिला व बालकल्याण विभाग,कर्ज सबसिडी,महिला स्वसहाय्य गटाचा सदस्य,6/15/2024
2,3,विद्यार्थी शिष्यवृत्ती योजना,शैक्षणिक कामगिरीच्या आधारे विद्यार्थ्यांना शिष...,शिक्षण विभाग,शिष्यवृत्ती,"मागास वर्गीय विद्यार्थी, ७५% पेक्षा जास्त गुण",4/30/2024
3,4,राज्य शासकीय नोकरी अर्ज,राज्य शासकीय सेवेसाठी अर्ज करण्याची ऑनलाइन प्र...,सामान्य प्रशासन विभाग,नोकरी,"१८-३८ वयोगट, संबंधित पात्रता",5/20/2024
4,5,मुफ्त आरोग्य तपासणी शिबिर,ग्रामीण भागात रहिवाशांसाठी विनामूल्य आरोग्य तप...,आरोग्य विभाग,आरोग्य सेवा,सर्व नागरिक,7/10/2024

In [7]:
df.isna().sum()

scheme_id      0
scheme_name    0
description    0
department     0
category       0
eligibility    0
deadline       0
dtype: int64

### Converting description field to vector using sbert model

In [4]:
import numpy as np
print(np.__version__)

2.3.3

In [3]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('l3cube-pune/marathi-sentence-similarity-sbert')

WARNING:tensorflow:From c:\Users\lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [8]:
df["description_vector"] = df["description"].apply(lambda x: model.encode(x))

In [10]:
df.head()

,scheme_id,scheme_name,description,department,category,eligibility,deadline,description_vector
0,1,शेतकरी अनुदान योजना,बियाण्यांसाठी शेतकऱ्यांना आर्थिक मदत देणारी योजना,कृषी विभाग,अनुदान,जमीन धारक शेतकरी,3/31/2024,"[-0.019805217, -0.018249715, -0.012199402, 0.0..."
1,2,महिला स्वसहाय्य गट योजना,महिला स्वसहाय्य गटांना व्यवसाय सुरू करण्यासाठी...,महिला व बालकल्याण विभाग,कर्ज सबसिडी,महिला स्वसहाय्य गटाचा सदस्य,6/15/2024,"[-0.026199086, 0.005875388, -0.0020529723, 0.0..."
2,3,विद्यार्थी शिष्यवृत्ती योजना,शैक्षणिक कामगिरीच्या आधारे विद्यार्थ्यांना शिष...,शिक्षण विभाग,शिष्यवृत्ती,"मागास वर्गीय विद्यार्थी, ७५% पेक्षा जास्त गुण",4/30/2024,"[-0.033258807, -0.0118139135, -0.0060276566, 0..."
3,4,राज्य शासकीय नोकरी अर्ज,राज्य शासकीय सेवेसाठी अर्ज करण्याची ऑनलाइन प्र...,सामान्य प्रशासन विभाग,नोकरी,"१८-३८ वयोगट, संबंधित पात्रता",5/20/2024,"[-0.016152378, -0.012807344, 0.019232813, 0.01..."
4,5,मुफ्त आरोग्य तपासणी शिबिर,ग्रामीण भागात रहिवाशांसाठी विनामूल्य आरोग्य तप...,आरोग्य विभाग,आरोग्य सेवा,सर्व नागरिक,7/10/2024,"[-0.013903189, -0.014410155, 0.0020151383, -0...."

In [9]:
es.ping()

True

### create new index in elasticsearch

In [ ]:
from src.elasticSearch.indexMappings import indexMappings
es.indices.create(index = "marathi_schemes" , mappings = indexMappings)

### insert data into index

In [10]:
record_list = df.to_dict("records")

In [11]:
record_list[8]

{'scheme_id': 9,
 'scheme_name': 'मोफत इंटरनेट सेवा',
 'description': 'शाळा-महाविद्यालयांमध्ये मोफत इंटरनेट सेवा पुरवठा',
 'department': 'तंत्रज्ञान विभाग',
 'category': 'सुविधा',
 'eligibility': 'शासकीय शैक्षणिक संस्था',
 'deadline': '9/1/2024',
 'description_vector': array([-3.28198932e-02, -1.22763366e-02, -9.14190989e-03, -1.26465010e-02,
         2.37572677e-02, -3.38627957e-02,  1.34045957e-03, -3.57055361e-03,
        -1.65964831e-02,  1.39760133e-02,  2.09304057e-02, -2.56308191e-03,
         1.75180901e-02, -9.02399793e-03, -7.20589515e-03, -1.53395403e-02,
        -3.63764848e-04, -6.04298245e-03,  1.57842580e-02, -8.94714706e-03,
         1.24763446e-02,  1.20191388e-02, -1.53071489e-02,  1.44403027e-02,
         1.84102952e-02, -1.46792829e-02, -6.14943868e-03,  1.93558692e-03,
        -9.39143170e-03,  1.02639608e-02,  1.71703126e-04,  8.83889385e-03,
         9.84950829e-03,  2.73562856e-02,  1.17094745e-03,  4.79097813e-02,
        -1.33460062e-02, -2.13035736e-02,  2.14185305e-02, -6.71292597e-04,
        -9.08012129e-03, -2.19326764e-02, -2.51326356e-02,  3.71920317e-02,
         4.65767225e-03,  1.58278160e-02,  1.70254782e-02, -7.19477842e-03,
         3.65354493e-02, -4.05713916e-02, -1.88559629e-02,  4.44667181e-03,
        -1.29571678e-02,  5.13000973e-03, -1.91091749e-04, -2.62029916e-02,
        -6.78092847e-03,  4.31047520e-03, -2.48277467e-03, -5.55251446e-03,
         1.00678597e-02, -3.70792719e-03, -1.43260900e-02, -6.29315991e-03,
         2.04287237e-03, -2.00165296e-03,  2.02667527e-02, -1.26532521e-02,
         7.78006110e-03,  9.56723280e-03, -7.47575331e-03,  9.03920829e-03,
         2.14470290e-02,  1.79588457e-03, -2.14970764e-03,  2.21081600e-02,
         3.91004421e-02,  2.11826013e-03, -2.71873316e-03, -5.21011092e-03,
        -3.87685548e-04,  6.15088129e-03, -7.78205518e-04, -3.46257770e-03,
         2.47213300e-02,  5.64762345e-03,  2.22154278e-02,  9.87727754e-03,
         7.45567901e-04,  1.88080408e-02, -1.17933273e-03,  1.33111402e-02,
        -6.58801664e-03, -7.95565359e-03,  1.15819909e-02, -4.40906751e-06,
         2.31979159e-03, -1.55025814e-02, -8.78463872e-03,  3.52657177e-02,
        -2.61769490e-03, -2.64052604e-03, -4.43211524e-03,  9.51769110e-03,
         2.01695878e-02,  6.34352583e-03,  5.49715362e-04,  1.72617957e-02,
        -1.67962648e-02, -1.26185939e-02, -4.71354648e-03,  7.94462673e-03,
         3.07125389e-03,  3.98751069e-03,  1.38783352e-02, -1.04151643e-03,
         1.68701634e-02,  4.05518862e-04,  1.95800848e-02,  1.93775855e-02,
        -1.56816505e-02, -1.38462801e-02, -2.13342067e-02,  1.93374418e-02,
         4.88550495e-03,  1.98209696e-02,  2.45733699e-03,  7.26443389e-03,
        -8.36226810e-03,  3.52947041e-03, -1.80801079e-02, -1.37478681e-02,
        -8.75647645e-03,  6.38285186e-03,  1.09810280e-02, -8.80965817e-05,
         2.12797262e-02,  6.04949053e-03,  2.09170915e-02, -1.76490657e-03,
         5.02167037e-03, -1.86764938e-03,  3.18301981e-03,  8.72834120e-03,
         3.75298294e-03,  1.47578744e-02,  6.59487303e-03, -2.11627930e-02,
        -5.15096122e-03, -8.45613904e-05, -9.11191758e-03, -4.70363954e-03,
         1.05369743e-02,  3.54131684e-03,  1.24190627e-02, -2.78904475e-02,
         1.22599853e-02,  8.32329853e-04, -1.16891069e-02, -6.38791639e-03,
        -1.57132442e-03,  2.06063148e-02,  9.08688270e-03,  2.65860511e-03,
         5.60635235e-03,  1.40198590e-02, -1.43591280e-03, -1.21083520e-02,
         1.47079173e-02,  1.72199830e-02,  1.77072771e-02, -5.46596013e-03,
         2.14019381e-02, -1.02261510e-02, -2.59713922e-02, -1.40327094e-02,
         9.24096536e-03, -2.56811269e-02,  1.17176110e-02,  7.32793752e-03,
        -1.48490891e-02, -9.72386741e-04,  1.36856791e-02, -1.73134152e-02,
        -1.77674536e-02,  1.91983730e-02,  1.65955556e-04,  5.99216484e-03,
        -9.12660384e-04,  1.06528383e-02,  6.41104346e-03,  2.96792202e-03,
         2.45601032e-02, -1.62223261e-02, -1.61520708e-02,  9.77655035e-03,
         2.05711722e-02, -3.41510251e-02,  1.59251094e-02,  3.64874373e-03,
         2.33535795e-03,  4.43968643e-03,  2.40082499e-02,  6.34781877e-03,
         7.23034423e-03, -5.71252126e-03, -1.58776883e-02, -2.34022290e-02,
        -7.52981286e-03, -2.01178901e-02, -1.11898975e-02, -9.51714907e-03,
         3.87404254e-03, -1.98863149e-02, -1.45269949e-02,  6.18969137e-03,
         2.31768638e-02, -2.56346110e-02, -1.32805463e-02, -3.19486810e-03,
         9.52435751e-03,  1.33630456e-02,  9.93044022e-03,  1.32483616e-02,
         5.46439644e-03,  8.43031053e-03, -3.46155977e-03, -2.15921160e-02,
        -6.87654770e-04,  2.17290260e-02, -1.84511896e-02, -4.49847523e-03,
         1.36410119e-02,  8.03141855e-03, -1.00858677e-02,  1.65946856e-02,
        -2.13453081e-03, -1.71581209e-02, -7.61772180e-03, -6.72171731e-03,
        -9.05419327e-03,  2.60802358e-02, -5.10922051e-04,  1.10681811e-02,
        -1.10511552e-03, -1.19415997e-02,  1.48390105e-03, -6.76068058e-03,
         2.18669907e-03,  4.62995432e-02,  9.91468318e-03, -1.21280979e-02,
         5.06209722e-03, -7.84622622e-04, -1.06713902e-02, -5.21586323e-03,
        -6.30576024e-03, -6.75616553e-03, -1.95285465e-04, -9.27418657e-03,
         8.13132338e-03, -1.79315358e-02,  2.91788522e-02,  1.26594372e-04,
         8.73093680e-03,  1.50158498e-02,  3.97271389e-04,  2.28466243e-02,
        -9.98817291e-03,  1.09069441e-02,  2.72360886e-03, -1.42221036e-03,
         3.73167801e-03,  9.42261051e-03,  1.54832648e-02,  3.41548165e-03,
        -4.83844429e-03, -6.37590140e-03,  1.64041929e-02, -6.23532850e-03,
         3.97568941e-03, -5.96214179e-03, -1.60050467e-02, -2.06858176e-03,
        -5.87221747e-03, -2.05316171e-02,  7.47261196e-03, -9.16270725e-03,
         7.24853063e-03,  6.99034985e-03, -2.30627693e-02, -7.84033630e-03,
        -3.65907280e-03, -1.33963209e-02,  6.04817132e-03, -2.17180364e-02,
        -1.94786750e-02,  1.76542290e-02, -1.05373245e-02, -9.55267902e-03,
        -5.31062204e-03,  5.23811718e-03, -3.95753514e-03,  8.84713884e-03,
         1.43697215e-02, -7.29011837e-04, -3.08389273e-02, -3.23480517e-02,
        -6.59831008e-03, -7.77887274e-03, -1.34065244e-02, -1.49562315e-03,
         3.01414840e-02, -3.18816630e-03,  1.67717133e-02,  4.32767048e-02,
        -3.26176211e-02, -2.20371149e-02, -8.53974838e-03,  8.76073973e-05,
         1.06123853e-02, -7.80220702e-03, -1.79075636e-02, -4.26196912e-03,
        -6.40496705e-03,  7.63839856e-03,  3.10740084e-03, -1.27529008e-02,
        -6.30094018e-03, -1.46185923e-02, -1.96812190e-02,  1.12565178e-02,
         2.88320775e-03, -2.76833237e-03,  3.30976065e-04, -1.95982563e-03,
         1.45814521e-02, -1.22664124e-02,  3.92428553e-03,  2.72705294e-02,
         9.15487763e-05, -2.49954453e-03, -1.26636745e-02,  9.12996847e-03,
        -9.71940346e-03,  1.95242767e-03,  2.47853138e-02, -6.17114082e-03,
         5.17909322e-03,  6.77092816e-04, -1.17630847e-02, -1.20137613e-02,
         1.34069072e-02, -4.01521480e-04,  4.15483344e-04,  1.18769808e-02,
         1.41522782e-02, -2.41026329e-03,  1.58669855e-02, -6.45387173e-03,
         6.44738367e-03,  9.80501343e-03,  6.68961788e-03, -1.10161619e-03,
         5.47780131e-04,  2.13995576e-02,  2.58134492e-02, -5.32583054e-03,
        -4.48276289e-03,  3.19889225e-02, -1.50065031e-02,  7.62379402e-03,
        -3.29668298e-02,  7.20813964e-03,  1.49486689e-02,  3.13245389e-03,
        -1.73506718e-02,  7.95642566e-03,  4.22291690e-03,  9.50714480e-03,
        -1.85358804e-02, -1.53447120e-02, -1.05890622e-02, -1.68354884e-02,
        -3.09662074e-02,  1.15650054e-02,  1.20919105e-02, -2.60008238e-02,
         4.86200384e-04,  2.54203007e-03,  1.25603657e-02, -2.11284868e-02,
        -3.98922935e-02,  2.31024586e-02,  7.50984484e-03,  8.58943723e-03,
         5.11906156e-03, -1.55179668e-02, -7.96066690e-03, -1.45631726e-03,
         2.00760551e-02, -3.30728777e-02,  1.69076473e-02,  9.09921364e-04,
        -6.61203667e-05, -1.67691745e-02,  1.25264153e-02, -1.34400502e-02,
        -1.69077180e-02, -3.11867148e-03,  4.72884579e-03,  3.04409629e-03,
         2.78892610e-02,  7.65904784e-03,  1.17968880e-02, -3.67255835e-03,
        -8.88024736e-03,  5.63001353e-03,  1.41458143e-03, -1.31735634e-02,
         1.09973568e-02, -7.80697167e-03,  1.29059551e-03, -3.32930736e-04,
        -2.11729202e-03, -2.27384008e-02, -3.07514779e-02,  1.06781209e-02,
         2.54800580e-02,  6.95483992e-03, -9.65811498e-03,  8.61195568e-03,
         9.72447451e-03, -1.06262416e-03,  7.60685513e-03,  4.43929574e-03,
         7.27414247e-03, -2.43080985e-02,  3.81463356e-02,  1.39242830e-02,
         5.04487474e-03,  3.09482170e-03,  1.84112824e-02,  1.71652175e-02,
         5.95783291e-04,  2.23610979e-02,  5.71626751e-03, -1.64839812e-03,
         2.61619035e-02,  6.01563742e-03,  1.02951890e-02, -8.25630780e-03,
         1.52740208e-02, -1.90858878e-02, -3.23544699e-03,  2.24410696e-03,
         1.65930651e-02, -1.04869483e-02, -7.06498092e-03,  3.18062678e-02,
        -2.30979752e-02, -2.76188273e-03,  5.02002332e-03,  4.76595992e-03,
        -3.78697691e-03, -5.73485019e-03,  1.32344095e-02, -2.77739055e-02,
         2.25874297e-02,  9.07330401e-03, -2.73452769e-03,  1.10736173e-02,
        -1.91698261e-02,  2.17110831e-02,  3.05552338e-03, -1.70778055e-02,
        -1.42538650e-02, -3.53327999e-03,  1.67849811e-03, -1.06872562e-02,
        -3.82139755e-04,  7.73968641e-05,  2.00663619e-02, -3.66145186e-03,
        -1.92212942e-03, -1.50031392e-02, -1.20487539e-02,  8.57876241e-03,
        -4.35210112e-03, -1.61829591e-03, -1.28442375e-02,  2.59341896e-02,
        -8.49219388e-04, -2.72316895e-02,  1.40681388e-02, -1.46797625e-02,
         6.04433566e-03,  9.97488480e-03, -8.84546991e-03,  6.78104302e-03,
         2.43853796e-02, -1.24043049e-02,  3.03493836e-03,  1.12111103e-02,
         1.16379987e-02,  3.69191123e-03,  3.30799329e-03, -1.06585519e-02,
         6.55470695e-03,  9.72231384e-04,  5.11089619e-03,  7.05519784e-03,
        -2.24041403e-04,  1.03846397e-02,  1.19323411e-03, -2.59754602e-02,
         9.34629701e-03, -6.85259467e-03, -5.40180132e-04,  4.25915513e-03,
        -1.87758263e-02, -1.62309483e-02,  3.22327092e-02,  8.37970898e-03,
        -1.66326351e-02,  1.49524957e-02,  2.13444093e-03,  9.95475892e-03,
        -7.00422749e-03,  1.79705508e-02,  1.57523975e-02, -1.93253793e-02,
        -2.02371590e-02,  1.18393702e-02, -3.79438922e-02, -3.07307579e-02,
         4.25837375e-03, -1.38305603e-02,  1.25834718e-02,  8.39956570e-03,
        -3.41660203e-03,  7.75429001e-03, -9.89445765e-03, -1.17623899e-02,
        -1.20994644e-02,  4.89107287e-03, -6.47125253e-03,  4.32311278e-03,
        -7.97224604e-03,  7.29765277e-04, -4.98490129e-03, -6.79011398e-04,
        -4.70075011e-03, -1.55345257e-02, -1.54077429e-02,  2.16467083e-02,
        -1.24489116e-02,  4.88465326e-03,  9.62053076e-04, -1.36709865e-02,
        -5.91045711e-03, -1.10844374e-02, -1.46358851e-02,  1.55315297e-02,
         5.59976092e-03,  9.32831503e-03,  1.65843032e-02,  9.11775976e-03,
        -2.33941786e-02,  6.08584960e-04, -2.68168263e-02, -1.91930924e-02,
        -2.04673540e-02, -6.59802463e-03,  3.58872977e-03,  4.04718565e-04,
         3.00812870e-02, -1.63815375e-02,  9.88657679e-03,  7.96611048e-03,
         4.95136250e-03, -3.26965074e-03,  2.80536624e-04, -2.44764183e-02,
         2.15594703e-03,  1.45783904e-03, -1.98279833e-03,  5.05283987e-03,
        -1.30502358e-02,  7.54053425e-03, -5.67011395e-03, -1.29220542e-02,
        -9.77325067e-03,  1.61838643e-02, -7.30211753e-03, -1.52936394e-04,
         2.24701278e-02, -1.42984418e-02, -1.00621143e-02,  1.38155399e-02,
        -1.61710978e-02,  4.21467833e-02,  1.19511541e-02, -7.43161747e-03,
        -1.10464764e-03, -3.18024978e-02,  2.36128829e-03,  2.42893081e-02,
        -2.41055451e-02, -5.40682161e-03, -9.97444801e-03, -8.99805222e-03,
         1.12570142e-02,  2.01668795e-02, -1.13806929e-02, -1.17430147e-02,
        -9.28455777e-03,  1.91014875e-02,  2.70771357e-04, -9.92173515e-03,
         2.45917011e-02,  5.01533877e-03, -1.47207025e-02,  2.77885789e-04,
        -3.99534078e-03, -1.09562427e-02,  2.40258686e-02, -1.86806475e-03,
         3.78405349e-03, -7.74131576e-03, -6.96745282e-03, -2.93273479e-04,
         7.06267962e-03, -6.50890451e-03,  1.15596456e-02, -2.85993028e-03,
        -2.40885792e-03,  1.66363548e-02, -2.54907403e-02, -7.70942122e-03,
         2.49900781e-02,  1.07466783e-02, -9.05651879e-03, -4.21282127e-02,
        -1.81273965e-03,  7.36442511e-04, -5.18259476e-04, -1.35220424e-03,
         9.57291294e-03,  1.19549278e-02, -2.48522423e-02,  2.00445391e-02,
         2.31195726e-02,  1.06717888e-02, -1.70933791e-02, -1.29559566e-03,
         6.16151746e-03, -2.23424453e-02, -1.14315189e-03,  2.35689292e-03,
         7.11820414e-03, -2.20077625e-03, -6.83200499e-03, -1.62947066e-02,
         9.53793875e-04, -1.33241415e-02,  1.08276354e-02, -1.44053157e-02,
        -1.33774970e-02, -7.16434885e-03,  2.52537057e-03, -1.22665744e-02,
        -1.51734231e-02, -6.74242387e-03, -1.18828071e-02,  3.28186667e-04,
        -6.20110286e-03,  5.15597360e-03, -7.79358670e-03,  4.02502436e-03,
         2.85596843e-03,  1.04132788e-02, -1.42031265e-02,  1.02866078e-02,
        -2.24437956e-02,  4.41704364e-03,  3.81620903e-03,  1.34552224e-02,
        -1.21038184e-02, -1.05424132e-02,  6.23203674e-03,  2.23684795e-02,
         1.63887423e-02,  4.45060339e-03, -5.82729327e-03,  4.27864902e-02,
         3.07416823e-02, -1.50354998e-02,  1.09131392e-02,  5.19872061e-04,
        -2.89899707e-02, -1.97357275e-02, -4.73937573e-04, -2.23110653e-02,
        -1.12974877e-02, -1.62663474e-03,  1.15761789e-03,  2.58605722e-02,
        -7.41354236e-03,  2.85347668e-03, -6.02112478e-03,  1.04026981e-02,
         1.47888409e-02, -3.26323393e-03, -6.05947152e-03, -8.36109184e-03,
         9.50897392e-03, -1.55530199e-02, -1.70261192e-03,  1.32691767e-02,
        -3.49213625e-03,  2.18273290e-02,  7.48365652e-03, -2.37485319e-02,
        -2.35947166e-02, -1.08902153e-04, -1.45307183e-02, -1.46708442e-02,
         1.11525971e-02, -1.60131662e-03,  1.60008911e-02,  2.22891150e-03,
        -1.35274250e-02,  2.49121105e-03, -3.10481701e-04, -6.29259786e-03,
        -7.81815313e-03,  8.43712408e-03, -2.07472574e-02, -8.96968134e-03,
         1.33899003e-02, -1.91202182e-02, -5.89439692e-03,  6.20561652e-03,
         1.21183051e-02,  3.13677313e-03, -2.55118799e-03, -6.66855415e-03,
         8.53341911e-03, -5.68762096e-03,  4.51877788e-02,  6.50686631e-03,
        -9.09545459e-03,  2.32164357e-02, -2.70291530e-02,  1.38311218e-02,
        -5.96954161e-03, -2.23887451e-02,  3.82860447e-03, -9.44794901e-03,
        -4.01405012e-03,  1.11450246e-02, -5.48980897e-03,  9.65829659e-03,
        -2.66506709e-02, -1.13751628e-02, -2.83553684e-03, -1.84326954e-02],
       dtype=float32)}

### convert all records into index in elastic search

In [12]:
from datetime import datetime

for record in record_list:
    try:
        if 'deadline' in record:
            val = record['deadline']
            # Convert only if it's a valid date
            try:
                # Parse MM/DD/YYYY and convert to YYYY-MM-DD
                record['deadline'] = datetime.strptime(val, "%m/%d/%Y").strftime("%Y-%m-%d")
            except:
                # If it's not a date (like "चालू"), set null
                record['deadline'] = None

        es.index(index="marathi_schemes", document=record, id=record['scheme_id'])
    except Exception as e:
        print("error", e)

In [13]:
es.count(index="marathi_schemes")

ObjectApiResponse({'count': 30, '_shards': {'total': 1, 'successful': 1, 'skipped': 0, 'failed': 0}})

## semantic search query

In [17]:
input_text = "आरोग्य"
vector = model.encode(input_text)

semantic_query = {
    "size": 2,
    "knn": {
        "field": "description_vector",
        "query_vector": vector.tolist(),
        "k": 2,
        "num_candidates": 10
    }
}

result = es.search(index="marathi_schemes", body=semantic_query, source=["scheme_name", "description"])
result['hits']['hits']

C:\Users\lenovo\AppData\Local\Temp\ipykernel_2348\2441922523.py:14: DeprecationWarning: Received 'source' via a specific parameter in the presence of a 'body' parameter, which is deprecated and will be removed in a future version. Instead, use only 'body' or only specific parameters.
  result = es.search(index="marathi_schemes", body=semantic_query, source=["scheme_name", "description"])

[{'_index': 'marathi_schemes',
  '_id': '5',
  '_score': 0.8631873,
  '_source': {'scheme_name': 'मुफ्त आरोग्य तपासणी शिबिर',
   'description': 'ग्रामीण भागात रहिवाशांसाठी विनामूल्य आरोग्य तपासणी शिबिर'}},
 {'_index': 'marathi_schemes',
  '_id': '22',
  '_score': 0.8544108,
  '_source': {'scheme_name': 'वृक्षारोपण अभियान',
   'description': 'जागतिक आरोग्यासाठी मोठ्या प्रमाणावर वृक्षारोपण करणे'}}]

## lexical search query

In [18]:
lexical_query = {
    "query": {
        "multi_match": {
            "query": input_text,
            "fields": ["scheme_name", "description"]
        }
    },
    "size": 5
}
result = es.search(index="marathi_schemes", body=lexical_query, source=["scheme_name", "description"])
result['hits']['hits']

C:\Users\lenovo\AppData\Local\Temp\ipykernel_2348\1820745983.py:10: DeprecationWarning: Received 'source' via a specific parameter in the presence of a 'body' parameter, which is deprecated and will be removed in a future version. Instead, use only 'body' or only specific parameters.
  result = es.search(index="marathi_schemes", body=lexical_query, source=["scheme_name", "description"])

[{'_index': 'marathi_schemes',
  '_id': '5',
  '_score': 2.8766742,
  '_source': {'scheme_name': 'मुफ्त आरोग्य तपासणी शिबिर',
   'description': 'ग्रामीण भागात रहिवाशांसाठी विनामूल्य आरोग्य तपासणी शिबिर'}}]

## Hybrid query

In [19]:
hybrid_query = {
    "size": 5,
    "query": {
        "bool": {
            "should": [
                {
                    "multi_match": {
                        "query": input_text,
                        "fields": ["scheme_name", "description"],
                        "boost": 0.4
                    }
                }
            ]
        }
    },
    "knn": {
        "field": "description_vector",
        "query_vector": vector.tolist(),
        "k": 5,
        "num_candidates": 20,
        "boost": 0.6
    }
}

result = es.search(index="marathi_schemes", body=hybrid_query, source=["scheme_name", "description"])
result['hits']['hits']

C:\Users\lenovo\AppData\Local\Temp\ipykernel_2348\3453183632.py:25: DeprecationWarning: Received 'source' via a specific parameter in the presence of a 'body' parameter, which is deprecated and will be removed in a future version. Instead, use only 'body' or only specific parameters.
  result = es.search(index="marathi_schemes", body=hybrid_query, source=["scheme_name", "description"])

[{'_index': 'marathi_schemes',
  '_id': '5',
  '_score': 1.6685821,
  '_source': {'scheme_name': 'मुफ्त आरोग्य तपासणी शिबिर',
   'description': 'ग्रामीण भागात रहिवाशांसाठी विनामूल्य आरोग्य तपासणी शिबिर'}},
 {'_index': 'marathi_schemes',
  '_id': '22',
  '_score': 0.5126465,
  '_source': {'scheme_name': 'वृक्षारोपण अभियान',
   'description': 'जागतिक आरोग्यासाठी मोठ्या प्रमाणावर वृक्षारोपण करणे'}},
 {'_index': 'marathi_schemes',
  '_id': '29',
  '_score': 0.50772965,
  '_source': {'scheme_name': 'मोफत दवाखाना',
   'description': 'ग्रामीण भागातील रुग्णांसाठी मोफत दवाखाना आणि औषधे'}},
 {'_index': 'marathi_schemes',
  '_id': '10',
  '_score': 0.48168054,
  '_source': {'scheme_name': 'कन्या प्रसूती सहाय्य योजना',
   'description': 'गरिबी रेषेखालील कुटुंबातील प्रसूतीसाठी आर्थिक मदत'}},
 {'_index': 'marathi_schemes',
  '_id': '28',
  '_score': 0.48094335,
  '_source': {'scheme_name': 'महात्मा फुले सामाजिक न्याय योजना',
   'description': 'सामाजिक न्यायासाठी चालविल्या जाणाऱ्या विविध उपक्रम'}}]