Connect to localhost:9200 of elasticSearch

In [1]:
from elasticsearch import Elasticsearch
es = Elasticsearch("http://localhost:9200",
                   basic_auth = ('elasticsearch', 'e3TKzHmKRFWBP4gY--cjeQ'),
                   request_timeout=60,
                   )
es.ping() 
print(es.info())

{'name': 'LAPTOP-ANN0J427', 'cluster_name': 'elasticsearch', 'cluster_uuid': '6AxnonBCTU-8fGsKa_EYMQ', 'version': {'number': '9.1.3', 'build_flavor': 'default', 'build_type': 'zip', 'build_hash': '0c781091a2f57de895a73a1391ff8426c0153c8d', 'build_date': '2025-08-24T22:05:04.526302670Z', 'build_snapshot': False, 'lucene_version': '10.2.2', 'minimum_wire_compatibility_version': '8.19.0', 'minimum_index_compatibility_version': '8.0.0'}, 'tagline': 'You Know, for Search'}

In [2]:
import pandas as pd
df = pd.read_csv('../../preprocessing/cleanedDataset.csv')
print(df.shape)
df.head()

(64, 5)

,scheme_id,site,scheme_name,description,scheme_link
0,1,https://mahafood.gov.in/provider/%E0%A4%B0%E0%...,आनंदाचा शिधा,दि. 04.10.2022 च्या शासन निर्णयानुसार राष्ट्री...,https://mahafood.gov.in/scheme/%e0%a4%86%e0%a4...
1,2,https://mahafood.gov.in/provider/%E0%A4%B0%E0%...,एपीएल शेतकरी,"राज्यातील छत्रपती संभाजीनगर, जालना, नांदेड, बी...",https://mahafood.gov.in/scheme/%e0%a4%8f%e0%a4...
2,3,https://mahafood.gov.in/provider/%E0%A4%B0%E0%...,शिवभोजन,राज्यातील गरीब व गरजू जनतेला सवलतीच्या दरात भो...,https://mahafood.gov.in/scheme/%e0%a4%b6%e0%a4...
3,4,https://maharashtra.gov.in/Site/1604/scheme,कृषी योजना,शेतकरी वर्गासाठी राज्य शासनातर्फे अनेक योजना उ...,https://www.manage.gov.in/fpoacademy/SGSchemes...
4,5,https://maharashtra.gov.in/Site/1604/scheme,कृषी तारण कर्ज योजना,शेतकऱ्याला असलेल्या आर्थिक गरजेपोटी तसेच स्थान...,https://www.msamb.com/Schemes/PledgeFinance

In [3]:
df.isna().sum()

scheme_id      0
site           0
scheme_name    0
description    0
scheme_link    0
dtype: int64

In [4]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('l3cube-pune/marathi-sentence-similarity-sbert')

WARNING:tensorflow:From c:\Users\lenovo\AppData\Local\Programs\Python\Python312\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [5]:
df["description_vector"] = df["description"].apply(lambda x: model.encode(x))

In [6]:
df.head()

,scheme_id,site,scheme_name,description,scheme_link,description_vector
0,1,https://mahafood.gov.in/provider/%E0%A4%B0%E0%...,आनंदाचा शिधा,दि. 04.10.2022 च्या शासन निर्णयानुसार राष्ट्री...,https://mahafood.gov.in/scheme/%e0%a4%86%e0%a4...,"[-0.03430499, -0.0051293606, 0.022085818, 0.00..."
1,2,https://mahafood.gov.in/provider/%E0%A4%B0%E0%...,एपीएल शेतकरी,"राज्यातील छत्रपती संभाजीनगर, जालना, नांदेड, बी...",https://mahafood.gov.in/scheme/%e0%a4%8f%e0%a4...,"[-0.03178832, -0.01153959, 0.0040703802, 0.006..."
2,3,https://mahafood.gov.in/provider/%E0%A4%B0%E0%...,शिवभोजन,राज्यातील गरीब व गरजू जनतेला सवलतीच्या दरात भो...,https://mahafood.gov.in/scheme/%e0%a4%b6%e0%a4...,"[-0.017393228, -0.0021912777, 0.0157103, 0.018..."
3,4,https://maharashtra.gov.in/Site/1604/scheme,कृषी योजना,शेतकरी वर्गासाठी राज्य शासनातर्फे अनेक योजना उ...,https://www.manage.gov.in/fpoacademy/SGSchemes...,"[-0.019458463, -0.012561898, -0.0048517943, 0...."
4,5,https://maharashtra.gov.in/Site/1604/scheme,कृषी तारण कर्ज योजना,शेतकऱ्याला असलेल्या आर्थिक गरजेपोटी तसेच स्थान...,https://www.msamb.com/Schemes/PledgeFinance,"[-0.017723113, -0.0029795915, 0.0073545375, 0...."

In [7]:
es.ping()

True

In [35]:
from indexMappings import indexMappings
es.indices.create(index = "schemes_mapping" , mappings = indexMappings)

ObjectApiResponse({'acknowledged': True, 'shards_acknowledged': False, 'index': 'schemes_mapping'})

generate index mappings

insert data into index

In [8]:
record_list = df.to_dict("records")

In [9]:
record_list[0]

{'scheme_id': 1,
 'site': 'https://mahafood.gov.in/provider/%E0%A4%B0%E0%A4%BE%E0%A4%9C%E0%A5%8D%E0%A4%AF-%E0%A4%B8%E0%A4%B0%E0%A4%95%E0%A4%BE%E0%A4%B0-mr/',
 'scheme_name': 'आनंदाचा शिधा',
 'description': 'दि. 04.10.2022 च्या शासन निर्णयानुसार राष्ट्रीय अन्नसुरक्षा अधिनियम, 2013 अंतर्गत अंत्योदय अन्न योजना, प्राधान्य कुटुंब तसेच औरंगाबाद व अमरावती विभागातील सर्व जिल्हे व नागपूर विभागातील वर्धा अशा 14 शेतकरी आत्महत्याग्रस्त जिल्ह्यांतील एपीएल केशरी शेतकरी शिधापत्रिकाधारकांना ई-पॅास प्रणालीद्वारे 1 किलो रवा, 1 किलो चणाडाळ, 1 किलो साखर व 1 लिटर पामतेल या 4 शिधाजिन्नसांचा समावेश असलेल्या विशेष शिधाजिन्नस संचांचे वितरण  100-प्रति संच या दराने करण्यात आले आहे. त्यानुसार मंजूर करण्यात आलेल्या 1.61 कोटी शिधाजिन्नस संचांपैकी 1.61 कोटी शिधाजिन्नस संचांचे सुमारे 100 पात्र शिधापत्रिकाधारकांना वितरण करण्यात आले आहे.',
 'scheme_link': 'https://mahafood.gov.in/scheme/%e0%a4%86%e0%a4%a8%e0%a4%82%e0%a4%a6%e0%a4%be%e0%a4%9a%e0%a4%be-%e0%a4%b6%e0%a4%bf%e0%a4%a7%e0%a4%be/',
 'description_vector': array([-3.43049914e-02, -5.12936059e-03,  2.20858175e-02,  7.74219539e-03,
         2.82565653e-02, -9.91985109e-03, -4.03571315e-03,  9.23226029e-03,
         8.11281335e-03,  1.03322195e-03,  8.72045173e-04,  1.06196264e-02,
         9.83992498e-03, -1.81763042e-02, -5.25347982e-03, -2.00595502e-02,
        -5.52726770e-03, -7.68145919e-03,  3.83548182e-03, -1.97888520e-02,
         6.15616888e-03, -1.16232196e-02, -1.32690128e-02,  1.02178743e-02,
         9.95635428e-03,  1.41091328e-02,  3.36631276e-02, -1.12010678e-02,
         1.58473086e-02,  1.24502508e-02, -1.64590012e-02, -1.52322641e-02,
         1.11759501e-02, -1.24793975e-02, -1.47179316e-03, -2.52346764e-03,
        -2.11245753e-03, -1.46145839e-02,  1.93673894e-02, -1.32602537e-02,
         1.07882898e-02, -8.99164937e-03, -1.66752767e-02, -1.32896462e-02,
        -4.18951269e-04, -2.33620219e-02,  1.63732078e-02,  1.80353094e-02,
        -7.73714250e-03, -3.30218533e-03, -1.03246048e-02, -1.90420318e-02,
        -1.08179897e-02, -1.93613302e-03,  1.74792003e-04,  4.00986569e-03,
         7.68905366e-03,  6.69789081e-03,  2.05962826e-03, -4.98060719e-04,
         8.22840165e-03,  2.48731468e-02, -6.42400188e-03, -2.63296273e-02,
         1.80473924e-02, -4.96733328e-03,  3.47781833e-03, -9.54820309e-03,
        -1.17052058e-02,  5.63210016e-03, -1.89254601e-02, -5.90440491e-03,
         9.47966427e-03,  7.90748838e-03, -1.22036422e-02,  4.87246923e-02,
         1.51145766e-02, -2.74047256e-02,  1.34719731e-02, -7.16013089e-03,
        -5.44183468e-03,  2.10288186e-02, -6.86760060e-03, -1.38676492e-03,
         1.96735691e-02,  6.14611898e-04,  1.85612999e-02,  1.63680688e-02,
         1.74221285e-02,  3.80131463e-03, -1.00859664e-02,  1.24901067e-02,
        -5.75284706e-03, -1.01807974e-02, -5.23533951e-03,  7.98625592e-03,
         1.28823109e-02, -3.27471271e-03,  5.90676907e-03, -1.31775055e-03,
        -3.30944662e-03,  2.52818177e-03, -3.44517292e-04,  4.42555593e-03,
        -1.20263360e-02,  5.55933733e-03,  1.34179890e-02,  2.30867211e-02,
        -5.77959884e-03,  8.55921395e-03,  5.05346712e-03, -5.12771355e-03,
        -2.22815443e-02,  3.18012782e-03,  2.09754929e-02, -3.40147573e-03,
        -3.80089227e-03,  9.32136830e-03, -4.95857140e-03, -2.11606920e-02,
         2.84364372e-02,  3.49693559e-03, -1.09490380e-02,  2.16281693e-02,
         2.08828552e-03,  1.31464633e-03, -2.31086668e-02,  7.39616202e-03,
         2.16097431e-03,  6.42723078e-03,  2.59710243e-03, -4.13781265e-03,
         1.44209256e-02, -7.60566629e-03, -4.69362916e-04, -1.46556068e-02,
        -3.18094552e-03,  1.27275800e-02,  1.25057623e-02, -3.17424815e-03,
        -7.19382777e-04, -5.75949298e-03, -9.16771498e-03, -5.57729136e-03,
         4.38278075e-03,  3.61851184e-03, -9.44011193e-03, -6.43020263e-03,
         6.37976732e-03, -1.16188472e-04, -9.43090301e-03,  3.19127738e-03,
         1.94351538e-03,  2.49501807e-03, -2.50476785e-03, -8.97019403e-04,
        -1.43250404e-02, -4.01057489e-03, -2.43187547e-02, -1.84866437e-03,
        -4.64034686e-03,  1.11853158e-04, -1.20544648e-02,  3.98405083e-03,
         7.95416418e-06,  2.45889602e-03,  2.72154633e-04, -1.68609209e-02,
        -2.77309977e-02,  3.71122435e-02,  3.82011235e-02,  1.19034306e-03,
         1.73175391e-02,  2.19500950e-03, -2.25111865e-03, -7.87973218e-03,
        -1.42248068e-02, -1.39048876e-04,  4.93913190e-03,  1.50624476e-02,
        -2.22907458e-02,  6.12863107e-03, -3.53378914e-02,  7.79226189e-03,
        -7.21148401e-03, -2.01763166e-03,  1.20458659e-02, -2.97026765e-02,
        -4.44299961e-03, -3.36829084e-03, -1.07503776e-02,  4.40128660e-03,
         1.93128129e-03, -7.39091588e-03,  1.73410736e-02, -3.22859362e-03,
         2.15123431e-03,  1.84383914e-02, -2.66056620e-02, -7.11458083e-03,
        -8.17023043e-04, -1.72595412e-03,  1.06071047e-02,  9.50829685e-03,
         1.57776580e-03,  2.20812089e-03, -3.81253310e-03,  4.01261589e-03,
         1.22587243e-02, -2.39649462e-03, -1.00940082e-03, -8.31852434e-04,
        -1.72087010e-02,  1.37409605e-02, -1.79744139e-02, -3.49529576e-03,
         1.36490790e-02,  3.01567023e-04, -5.91053208e-03,  9.99854691e-03,
         5.61733125e-03,  6.05215365e-03, -8.83892272e-03,  2.77502146e-02,
         7.27973413e-03,  1.18853187e-03,  1.60100311e-02, -1.55484239e-02,
         5.18015446e-03, -1.07493335e-02,  4.64138022e-04, -9.27394349e-03,
        -1.21551156e-02,  1.90652516e-02,  4.17725788e-03, -2.11938401e-03,
        -1.85093954e-02, -6.70011446e-04, -7.54975341e-03, -1.05601577e-02,
        -1.90810169e-04,  2.76312651e-03,  1.28890423e-03, -1.50040938e-02,
        -2.37733684e-02, -8.16596858e-03,  2.10756864e-02, -1.19044846e-02,
         2.11495999e-02, -3.89632024e-03,  1.08554019e-02,  1.04202200e-02,
         5.42501314e-03,  1.68222003e-02, -6.85017696e-03,  5.97190717e-03,
        -8.22250557e-04, -6.74768444e-03, -4.57057124e-03, -7.73520616e-04,
        -1.99977076e-03, -2.30802055e-02,  2.16758507e-03, -6.80151425e-05,
        -2.81739770e-03,  1.85986329e-02, -1.34031335e-02,  1.17353788e-02,
        -1.01303644e-02, -1.39837544e-02, -1.57219972e-02,  1.29958084e-02,
        -1.98861323e-02,  3.93283973e-03, -3.84591171e-03, -1.86556391e-02,
         1.38034835e-03, -1.80623364e-02,  1.05554676e-02,  1.94135806e-04,
         5.74499893e-04, -1.83748500e-03, -7.30913365e-03,  1.04681123e-02,
        -7.29071558e-04, -9.18404199e-03, -2.00643972e-03, -4.78865625e-03,
        -2.00525150e-02, -1.37188947e-02,  1.55533860e-02, -8.42946302e-03,
        -1.80060528e-02,  5.78742381e-03,  8.31068028e-03, -8.25924985e-03,
        -2.56052483e-02, -2.24630535e-03,  4.40023141e-03, -7.99913798e-03,
         2.95671704e-03,  3.09300981e-02, -2.15760432e-02,  5.50528802e-03,
         2.14078184e-02,  2.74139885e-02,  3.37362057e-03, -1.37726935e-02,
        -4.51231096e-03, -1.93460507e-03, -1.15775606e-02, -7.25610415e-04,
         2.04090048e-02,  1.59460807e-03,  4.16698959e-03,  6.55275071e-03,
         7.84601085e-03,  1.14546828e-02,  5.35506802e-03, -1.60269495e-02,
        -2.12492887e-02, -1.47400619e-02, -1.26178591e-02,  2.39658523e-02,
        -7.32957060e-03,  1.34843076e-03,  6.69069448e-03,  4.10123728e-03,
        -1.44103123e-03,  1.62994526e-02, -1.51404059e-02, -9.33924876e-03,
        -4.73432970e-04, -5.24649955e-03, -2.21874192e-03,  3.40667507e-03,
         9.45264380e-03,  7.29704602e-03,  3.07060219e-03,  4.50167358e-02,
         1.67937076e-04, -1.01447967e-03,  7.48976599e-03, -1.73418468e-03,
        -2.21383059e-03, -7.48935482e-03,  2.49948185e-02, -6.45719748e-03,
        -1.22452620e-02,  1.30259781e-03, -5.78778051e-03, -1.21359574e-02,
         1.38579160e-02, -5.43806469e-03, -8.77006270e-04,  6.31303946e-03,
        -8.15745792e-04, -1.57753918e-02,  2.32407634e-04,  9.06677917e-03,
         1.09197851e-02,  1.68822408e-02,  1.48204789e-02,  1.33169712e-02,
        -5.55246929e-03,  1.87488887e-02,  1.18973164e-03,  3.91761120e-03,
        -1.55133205e-02,  6.34525251e-03, -8.05966184e-03, -1.24671427e-03,
         3.06730438e-03,  1.87035296e-02,  2.35691648e-02, -3.84071562e-03,
        -1.54147269e-02, -7.46953860e-03,  3.34840128e-03,  7.57569587e-03,
        -1.64085105e-02, -8.19054060e-03, -1.33438520e-02, -2.04577036e-02,
        -1.80432375e-03,  1.15185920e-02,  1.65341608e-02, -1.50874751e-02,
        -8.10291059e-03,  1.54551957e-02,  1.68096218e-02, -2.24962533e-02,
        -6.88022655e-03, -6.86091371e-03, -1.29094189e-02,  6.76609715e-03,
         2.38045678e-03, -1.90973729e-02,  2.30616014e-02, -1.72910355e-02,
         1.42567530e-02,  9.79972770e-04,  9.64362361e-03,  1.41307246e-02,
        -3.82832997e-03, -1.41285416e-02,  1.03534071e-03,  7.76434503e-03,
         1.25038112e-02,  2.58218050e-02,  3.12630204e-03,  9.17945150e-03,
         1.60421226e-02, -4.03358042e-03,  1.79722086e-02,  1.36795621e-02,
        -7.37974001e-03,  1.71368644e-02, -8.07249732e-03, -1.05763960e-03,
         1.53906457e-03, -1.38817430e-02, -9.54885501e-03,  1.54986978e-02,
        -2.14938959e-03,  1.15062362e-02, -4.73196292e-03,  4.93046222e-03,
         2.25629583e-02, -1.63094141e-02,  5.76811261e-04, -9.39740799e-03,
        -5.01131173e-03,  1.17773225e-03,  1.19762830e-02, -1.33660166e-02,
        -9.65267420e-03, -2.46745963e-02, -1.81180742e-02,  7.74531579e-03,
        -1.43712841e-03, -6.65603112e-03, -2.03863034e-04, -9.83405509e-04,
        -1.56282622e-03, -8.62748455e-03, -4.44728794e-04, -1.45348692e-02,
         1.20103341e-02,  1.75141580e-02,  1.39032435e-02,  4.26022522e-03,
        -2.94458331e-03,  8.41635745e-03,  3.34886019e-03,  2.22173575e-02,
         8.06098245e-03, -2.39745062e-02, -1.02809360e-02,  4.95250290e-03,
        -1.05383135e-02,  4.19480912e-03,  8.61603621e-06,  2.46639783e-03,
         7.99743179e-03, -1.12486002e-03,  3.62356496e-03, -1.33119002e-02,
         4.03839769e-03,  1.46029945e-02,  5.78959333e-03,  5.50373318e-03,
        -2.14530043e-02,  2.96179694e-03,  6.93432009e-03,  3.00154043e-03,
        -1.01317922e-02, -1.90043878e-02,  2.92919064e-03, -8.87923036e-03,
        -1.44039011e-02,  2.09132489e-03, -7.31021678e-03, -1.48753198e-02,
        -1.56984292e-02, -2.63463566e-03,  3.49037163e-03,  3.44364438e-03,
         4.37349360e-03,  1.18106771e-02, -1.43455053e-02,  4.09374433e-03,
         3.74192419e-03, -1.54678011e-03,  1.62403323e-02,  1.08204372e-02,
        -1.98990828e-03, -1.00295600e-02, -6.75451709e-04,  9.28131305e-03,
         5.60064451e-04, -1.41448225e-03, -8.43530800e-03, -9.16800741e-03,
        -3.96408048e-03,  4.11717425e-04,  7.83413183e-03, -1.25202239e-02,
        -7.92143284e-04,  4.01370181e-03,  9.37676616e-03, -7.11299386e-03,
        -2.08889730e-02,  1.09208899e-03,  8.03171191e-03,  2.47347876e-02,
         1.47578306e-02, -8.77435040e-03, -1.57091345e-04,  9.65109619e-04,
        -6.43993495e-03, -8.66136700e-03,  4.63423505e-03, -1.16265966e-02,
         1.70754944e-03,  5.01600467e-03, -3.36122583e-03,  5.73503645e-03,
         3.59864673e-03,  2.23640329e-03, -1.26511455e-02, -2.20371503e-02,
        -1.02705071e-02, -2.93564564e-03, -3.68625186e-02,  4.53831482e-04,
        -1.61045082e-02, -3.58524150e-03, -2.94695445e-03, -1.57814205e-03,
         1.48228491e-02,  1.92627255e-02, -9.43890307e-03, -5.85069787e-03,
        -8.28542281e-03, -1.02814725e-02,  8.83904565e-03, -3.47375451e-03,
         2.43892515e-04, -3.99652831e-02, -2.95442995e-03,  1.82424840e-02,
         9.18540265e-03, -5.04967803e-03, -5.54924924e-03,  3.36730992e-03,
        -4.88875341e-03,  7.42237177e-03,  6.59324136e-03, -5.84375858e-03,
         1.29213883e-02,  5.41102607e-03,  2.08458882e-02, -9.16937552e-03,
        -3.79001047e-03, -1.40579883e-02, -3.82479141e-03,  4.08852100e-03,
        -6.66164514e-03,  5.90129336e-03, -1.93385649e-02, -3.74035537e-03,
        -7.77708460e-03,  3.61775584e-03,  9.02272668e-03,  2.03031339e-02,
         5.04375016e-03, -6.86964812e-03,  1.95892341e-02,  2.77312230e-02,
         1.93964113e-02, -4.62946072e-02, -4.52262396e-03, -8.13317299e-03,
         1.53772002e-02, -6.20699162e-03, -3.39288148e-03, -1.37860270e-03,
        -1.33464010e-02, -2.26575998e-03,  2.48536235e-03, -1.82302240e-02,
         1.17001403e-02,  5.91101777e-03,  1.46550648e-02, -2.01332569e-03,
        -1.17123155e-02,  1.92141123e-02,  5.61222201e-03, -1.62474252e-02,
        -9.70915705e-03,  2.04712711e-02,  7.01908488e-03,  8.16784613e-03,
        -2.44097947e-03, -3.22018936e-02,  1.14109777e-02,  9.42549761e-03,
         1.81892365e-02, -1.62336752e-02, -1.15947742e-02,  9.23314411e-03,
        -1.00540332e-02,  6.36660203e-04,  9.29645821e-03,  6.91124564e-03,
         2.38278601e-03,  1.71582354e-03, -3.49058118e-03, -1.67206079e-02,
         1.06771719e-02,  1.65250823e-02, -1.56430602e-02,  2.64927541e-04,
         6.12186547e-03,  2.14476534e-03, -1.29046170e-02,  1.69002207e-03,
        -4.05415660e-03, -4.96485224e-03,  9.45119187e-03,  4.67915181e-03,
        -1.39116531e-03, -7.61196809e-03,  1.88862700e-02, -1.03390971e-02,
        -1.98299764e-03,  1.13608846e-02,  6.44193147e-04,  2.52211676e-03,
         2.34858301e-02,  3.64817702e-03, -1.47234350e-02,  6.90072589e-03,
        -2.98855314e-03,  3.28906463e-03,  9.52643529e-03,  6.23329403e-03,
         6.61855051e-03,  1.58712622e-02,  4.20690048e-03,  2.57810159e-03,
         1.24949659e-03, -3.70570365e-03, -4.76889778e-03, -2.55389442e-03,
         6.02009241e-03, -6.08294678e-04,  1.73455745e-03, -2.91682314e-02,
        -6.45520305e-03,  1.02023128e-02, -5.91286318e-03,  1.80102065e-02,
        -2.80191400e-03, -2.31461739e-03, -3.54778813e-03,  1.30229732e-02,
         9.05885641e-03, -5.72541775e-03,  3.52532370e-03,  7.15037948e-03,
         7.84788397e-04, -2.06504622e-03,  4.41415422e-03,  1.15299132e-03,
         4.74832859e-03,  5.37585840e-03, -1.06088025e-02, -6.99293381e-03,
         9.49982146e-04, -9.85345989e-03, -2.08683070e-02, -1.60132553e-02,
        -2.14154106e-02,  4.69071418e-03,  8.55016056e-03,  5.44668734e-03,
        -3.24499165e-03, -1.11111645e-02,  2.17006505e-02,  2.09687208e-03,
         8.18520132e-03, -2.09660381e-02,  1.89607823e-03,  1.24212662e-02,
        -8.18921253e-04,  3.94314295e-04, -5.70861914e-04, -9.73401777e-03,
        -1.41799143e-02, -3.41164414e-03,  1.55797461e-02,  1.93650043e-03,
        -3.06720310e-03, -4.95682983e-03,  1.55541729e-02,  2.76812296e-02,
         1.88477058e-02, -1.14910984e-02,  6.25625765e-03,  5.28567564e-03,
         5.73344342e-03,  4.94273985e-03,  2.94522638e-03,  6.90102484e-03,
         1.32599184e-02,  9.80761461e-03, -1.13141946e-02,  2.69108638e-02,
        -1.93778649e-02, -4.92228568e-03,  1.34320464e-03, -3.98978638e-03,
         3.25366331e-04,  1.09441392e-02, -1.17358165e-02, -1.38177872e-02,
         4.20718780e-03, -1.63313514e-03,  5.76092396e-03,  1.34693794e-02,
        -1.06166943e-03, -3.69786914e-03, -1.06170810e-04, -2.87309079e-03,
         7.15303293e-04,  4.40240372e-03, -5.15588894e-02, -1.81939930e-03,
         8.22752994e-03,  4.96821757e-03, -9.37375240e-03, -2.68634446e-02,
        -1.09057222e-03,  6.69023022e-03, -1.78736635e-02, -1.84742138e-02,
         7.46104214e-03, -7.66500540e-04,  5.18662063e-03,  4.98747360e-03,
         1.34963850e-02,  9.05457512e-03, -1.63506716e-02,  7.15589151e-03,
        -7.52039533e-03, -2.30550002e-02,  1.23265097e-02, -2.85201725e-02,
        -3.02043371e-03, -3.01328185e-03,  4.53577004e-03, -1.25527941e-02,
        -2.78420281e-03,  1.28676491e-02, -7.05408957e-03,  1.75641943e-02],
       dtype=float32)}

In [21]:
es.ping()

True

In [11]:
for record in record_list:
    try:
        es.index(index="schemes_mapping", document=record, id=record['scheme_id'])
    except Exception as e:
        print("error", e)

In [26]:
print(es.cluster.health())

{'cluster_name': 'elasticsearch', 'status': 'yellow', 'timed_out': False, 'number_of_nodes': 1, 'number_of_data_nodes': 1, 'active_primary_shards': 7, 'active_shards': 7, 'relocating_shards': 0, 'initializing_shards': 0, 'unassigned_shards': 3, 'unassigned_primary_shards': 0, 'delayed_unassigned_shards': 0, 'number_of_pending_tasks': 0, 'number_of_in_flight_fetch': 0, 'task_max_waiting_in_queue_millis': 0, 'active_shards_percent_as_number': 70.0}

In [12]:
es.count(index="schemes_mapping")

ObjectApiResponse({'count': 64, '_shards': {'total': 1, 'successful': 1, 'skipped': 0, 'failed': 0}})

In [13]:
input_text = "आरोग्य"

## lexical search query

In [14]:
lexical_query = {
    "query": {
        "multi_match": {
            "query": input_text,
            "fields": ["scheme_name", "description"]
        }
    },
    "size": 5
}
result = es.search(index="marathi_schemes", body=lexical_query, source=["scheme_name", "description"])
result['hits']['hits']

C:\Users\lenovo\AppData\Local\Temp\ipykernel_27936\1820745983.py:10: DeprecationWarning: Received 'source' via a specific parameter in the presence of a 'body' parameter, which is deprecated and will be removed in a future version. Instead, use only 'body' or only specific parameters.
  result = es.search(index="marathi_schemes", body=lexical_query, source=["scheme_name", "description"])

[{'_index': 'marathi_schemes',
  '_id': '5',
  '_score': 2.8766742,
  '_source': {'scheme_name': 'मुफ्त आरोग्य तपासणी शिबिर',
   'description': 'ग्रामीण भागात रहिवाशांसाठी विनामूल्य आरोग्य तपासणी शिबिर'}}]

## semantic search query

In [18]:

vector = model.encode(input_text)

query = {
    "size": 2,
    "knn": {
        "field": "description_vector",
        "query_vector": vector.tolist(),
        "k": 2,
        "num_candidates": 10
    }
}

result = es.search(index="schemes_mapping", body=query, source=["scheme_name", "description"])
result['hits']['hits']

C:\Users\lenovo\AppData\Local\Temp\ipykernel_27936\982302055.py:13: DeprecationWarning: Received 'source' via a specific parameter in the presence of a 'body' parameter, which is deprecated and will be removed in a future version. Instead, use only 'body' or only specific parameters.
  result = es.search(index="schemes_mapping", body=query, source=["scheme_name", "description"])

[{'_index': 'schemes_mapping',
  '_id': '33',
  '_score': 0.8570445,
  '_source': {'scheme_name': 'राज्य शासन योजना',
   'description': 'आयुष चारित्र्य प्रमाणपत्र देणे आयुष अभ्यास प्रमाणपत्र देणे इस्सू ऑफ नो ओबजेशन सिर्तीफिकॅते आयुष ना देय प्रमाणपत्र देणे आयुष कीरकोळ जखम यांचे प्रमाणपत्र देणे आयुष कार्यमुक्त प्रमाणपत्र देणे आयुष वैद्यकीय प्रमाणपत्र देणे'}},
 {'_index': 'schemes_mapping',
  '_id': '57',
  '_score': 0.82223785,
  '_source': {'scheme_name': 'राज्य शासन योजना',
   'description': 'Changing the name of the business HealthFree Cancellation of license HealthFree Cancellation of license ProjectionFree Cancellation of license AdvertisementFree Change in Name of Business Glow SignFree Cancellation of license Glow SignFree'}}]

## hybrid search query

In [20]:
hybrid_query = {
    "size": 3,
    "query": {
        "bool": {
            "should": [
                {
                    "multi_match": {
                        "query": input_text,
                        "fields": ["scheme_name", "description"],
                        "boost": 0.4
                    }
                }
            ]
        }
    },
    "knn": {
        "field": "description_vector",
        "query_vector": vector.tolist(),
        "k": 5,
        "num_candidates": 20,
        "boost": 0.6
    }
}

result = es.search(index="marathi_schemes", body=hybrid_query, source=["scheme_name", "description"])
result['hits']['hits']

C:\Users\lenovo\AppData\Local\Temp\ipykernel_27936\1345303772.py:25: DeprecationWarning: Received 'source' via a specific parameter in the presence of a 'body' parameter, which is deprecated and will be removed in a future version. Instead, use only 'body' or only specific parameters.
  result = es.search(index="marathi_schemes", body=hybrid_query, source=["scheme_name", "description"])

[{'_index': 'marathi_schemes',
  '_id': '5',
  '_score': 1.6685821,
  '_source': {'scheme_name': 'मुफ्त आरोग्य तपासणी शिबिर',
   'description': 'ग्रामीण भागात रहिवाशांसाठी विनामूल्य आरोग्य तपासणी शिबिर'}},
 {'_index': 'marathi_schemes',
  '_id': '22',
  '_score': 0.5126465,
  '_source': {'scheme_name': 'वृक्षारोपण अभियान',
   'description': 'जागतिक आरोग्यासाठी मोठ्या प्रमाणावर वृक्षारोपण करणे'}},
 {'_index': 'marathi_schemes',
  '_id': '29',
  '_score': 0.50772965,
  '_source': {'scheme_name': 'मोफत दवाखाना',
   'description': 'ग्रामीण भागातील रुग्णांसाठी मोफत दवाखाना आणि औषधे'}}]